#!/system/xbin/bash 
#Maafkan Kegabutan Ku Ster :V
#bwahaha

blue='\033[34;1m'
green='\033[32;1m' 
purple='\033[35;1m'
cyan='\033[36;1m'
red='\033[31;1m'
white='\033[37;1m' 
yellow='\033[33;1m' 

echo $red "Rafell Itu Gans 😎😍"
sleep 1
clear
echo $blue "Rafell Itu Gans 😎😍"
sleep 1
clear
echo $green "Rafell Itu Gans 😎😍"
sleep 1
clear
echo $red "Rafell Itu Ganss 😎😍"
sleep 
clear
echo $blue "Rafell Itu Gans 😎😍"
sleep 1
clear
echo $green "Rafell Itu Ganss 😎😍"
sleep 1
clear
echo $red "Rafell Itu Ganss 😎😍"
sleep 1
clear
echo $blue "Rafell Itu Gans 😎😍"
sleep 1
clear
echo $green "Lu Buriq Tq"
sleep 1
clear 

echo "\033[1;31m]+=====%%@ @%%==================++ coded by : Mr.F3eLL ++ Team : BlackHat Hacker Indonesia ++ Contak me : 081316826548 ++==============================+ ^...^ ^...^ <_* *_> KoutaFree(Tree) <_* *_> \_/ \_/ ";
echo $green"MenuPaketanFree";
echo $blue"1.30GB (Tree)";
echo $purple"2.10GB (Tree)";
echo $yellow"3.2.75GB (Tree)";
echo $green"4.5GB (Tree)"
echo $red"00.Ini namanya Out"
read -p "[>>" stc 

if [ $stc = 1 ]
then 
clear
echo "MasukanNomerMu"|lolcat
read no
echo "Wait Tunggu"|lolcat
echo "$no, Sukses Gan"
fi 

if [ $stc = 2 ]
then 
clear
echo "MasukanNomerMu"|lolcat
read no
echo "Wait Tunggu"|lolcat
echo "$no, Sukses Gan"|lolcat
fi 

if [ $stc = 3 ]
then 
clear
echo "MasukanNomerMu"|lolcat
read no
echo "Wait Tunggu"|lolcat
echo "$no, Sukses Gan"|lolcat
fi 

if [ $stc = 4 ]
then 
clear
echo "MasukanNomerMu"|lolcat
read no
echo "Wait 5menit"|lolcat
echo "$no, Sukses Gan"|lolcat
fi 

if [ $stc = 00 ]
then 
clear
echo "Apakah Rafell Gans?"|lolcat
read ganss
echo "$ganss, Tq Gan"|lolcat
fi
